from enum import Enum

class NodeType(str, Enum):
    DATASOURCE = "DATASOURCE"
    DATASET = "DATASET"
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"
    MODEL = "MODEL"

class EdgeType(str, Enum):
    DATA_COLLECTION = "DATA_COLLECTION"
    DATA_CLEANING = "DATA_CLEANING"
    DATA_LABELING = "DATA_LABELING"
    DATA_SYNTHESIS = "DATA_SYNTHESIS"
    DATA_RATIO = "DATA_RATIO"
